name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install -g yarn
    - name: Install dependencies
      run: yarn install
    - name: Test & Build
      run: yarn pack
    
